#!/bin/bash

#Sarah Turner
#project 4 CS344
#Due June 9, 2019
#sweet compiling script to cut down on the time 

gcc -o otp_enc_d otp_enc_d.c
gcc -o otp_enc otp_enc.c
gcc -o otp_dec_d otp_dec_d.c
gcc -o otp_dec otp_dec.c
gcc -o keygen keygen.c 
